# Generated by Django 5.2.8 on 2025-11-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='polly_api_key',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
