# Generated by Django 5.2.8 on 2025-11-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_polly_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='polly_api_key',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
